
import '../styles/globals.css'
import MainLayout from "@/components/layouts/MainLayout"


export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="pt-br">
      <body>

        <MainLayout>
          
        {children}
        
        </MainLayout>
        
        </body>
    </html>
  )
}
