import React from 'react'
import '../styles/globals.css'
import Navbar from '../components/Navbar/Navbar'



export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="pt-br">
      <body className="bg-gradient-to-br from-indigo-300 via-purple-800 to-blue-200">

      <Navbar />
          
        {children}
        
        
        </body>
    </html>
  )
}
